"""
Lista de agravos do SINAN a trazer pro hub -- prefixos confirmados
diretamente na listagem real do FTP (não são chutados).

Cada entrada vira um parquet PRÓPRIO no bucket (sinan/{nome_arquivo}),
não um arquivo único mesclado -- agravos diferentes têm estruturas de
campos diferentes entre si, então misturar tudo n uma tabela só não
faria sentido.
"""

AGRAVOS_SINAN = [
    # (prefixo, nome_arquivo_final)
    ("DENG", "dengue"),
    ("CHIK", "chikungunya"),
    ("ZIKA", "zika"),
    ("TUBE", "tuberculose"),
    ("VIOL", "violencia_interpessoal_autoprovocada"),
    ("SIFA", "sifilis_adquirida"),
    ("SIFC", "sifilis_congenita"),
    ("SIFG", "sifilis_em_gestante"),
    ("HANS", "hanseniase"),
    ("AIDA", "aids_adulto"),
    ("AIDC", "aids_crianca"),
    ("HIVA", "hiv_adulto"),
    ("HIVC", "hiv_crianca"),
    ("HIVE", "hiv_gestante"),
    ("HIVG", "hiv_outro_perfil"),
    ("HEPA", "hepatites_virais"),
    ("MALA", "malaria"),
    ("LEPT", "leptospirose"),
    ("CHAG", "doenca_de_chagas_aguda"),
    ("ESQU", "esquistossomose"),
    ("LEIV", "leishmaniose_visceral"),
    ("LTAN", "leishmaniose_tegumentar_americana"),
    ("MENI", "meningite"),
    ("PNEU", "doenca_pneumococica_invasiva"),
    ("DIFT", "difteria"),
    ("COQU", "coqueluche"),
    ("TETA", "tetano_acidental"),
    ("TETN", "tetano_neonatal"),
    ("ANIM", "acidente_por_animal_peconhento"),
    ("FMAC", "febre_maculosa"),
    ("ACBI", "acidente_trabalho_material_biologico"),
    ("ACGR", "acidente_trabalho_grave"),
    ("CANC", "cancer_relacionado_ao_trabalho"),
    ("DERM", "dermatose_ocupacional"),
    ("LER", "ler_dort"),
    ("LERD", "ler_dort_detalhado"),
    ("MENT", "transtorno_mental_relacionado_ao_trabalho"),
    ("PAIR", "perda_auditiva_indzuida_por_ruido"),
    ("PEST", "peste"),
    ("ANTR", "antraz"),
    ("BOTU", "botulismo"),
    ("COLE", "colera"),
    ("TRAC", "tracoma"),
    ("RAIV", "raiva_humana"),
    ("HANT", "hantavirose"),
    ("FTIF", "febre_tifoide"),
    ("TOXC", "toxoplasmose_congenita"),
    ("TOXG", "toxoplasmose_gestacional"),
    ("PFAN", "paralisia_flacida_aguda"),
    ("ROTA", "rotavirus"),
    ("SDTA", "surto_doenca_transmitida_por_alimentos"),
    ("IEXO", "intoxicacao_exogena"),
    ("SRC", "sindrome_da_rubeola_congenita"),
    ("EXAN", "doenca_exantematica_suspeita"),
    ("VARC", "varicela_grave"),
    ("DCRJ", "doenca_de_chagas_reacao_transfusional"),
    ("NTRA", "notificacao_acidente_trabalho"),
    ("ESPO", "esporotricose"),
]